version: "3.8"
services:
  dashy:
    image: lissy93/dashy:latest
    container_name: dashy
    volumes:
      - /home/ptc/docker/dashy/conf.yml:/app/public/conf.yml
    networks:
      - inside
    ports:
      - 8080:80
    restart: unless-stopped
    # Configure healthchecks
    #healthcheck:
    #test: ['CMD', 'node', '/app/services/healthcheck']
    #interval: 1m30s
    #timeout: 10s
    #retries: 3
    #start_period: 40s
networks:
  inside:
    external: true
