version: "3.8"
name: cloudflared
services:
  cloudflared-foundry:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-foundry
    restart: unless-stopped
    networks:
      - outside
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=$FOUNDRY_TOKEN
  cloudflared-authentik:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-authentik
    restart: unless-stopped
    networks:
      - outside
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=$AUTHENTIK_TOKEN
networks:
  outside:
    external: true
