version: "3.3"
services:
  uptime-kuma:
    container_name: uptime-kuma
    restart: always
    networks:
      - inside
    ports:
      - 3001:3001
    volumes:
      - /home/ptc/docker/uptime-kuma:/app/data
    image: louislam/uptime-kuma:1
volumes:
  uptime-kuma: {}
networks:
  inside:
    external: true
